import type { Preset, PresetId } from '../partTypes'

export const presets: Record<PresetId, Preset> = {
  'preset-01': {
    skinTone: 'celeste',
    hair: 'cap',
    hairColor: 'celeste',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'square',
  },
  'preset-02': {
    skinTone: 'ivory',
    hair: 'fringe',
    hairColor: 'black',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'none',
  },
  'preset-03': {
    skinTone: 'bronze',
    hair: 'afro',
    hairColor: 'black',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'round',
  },
  'preset-04': {
    skinTone: 'golden',
    hair: 'beanie',
    hairColor: 'black',
    eyes: 'narrow',
    mouth: 'neutral',
    beard: 'goatee',
    glasses: 'none',
  },
  'preset-05': {
    skinTone: 'golden',
    hair: 'bald',
    hairColor: 'espresso',
    eyes: 'round',
    mouth: 'smile',
    beard: 'full',
    glasses: 'square',
  },
  'preset-06': {
    skinTone: 'ivory',
    hair: 'long',
    hairColor: 'auburn',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'round',
  },
  'preset-07': {
    skinTone: 'cocoa',
    hair: 'buzz',
    hairColor: 'black',
    eyes: 'round',
    mouth: 'smile',
    beard: 'stubble',
    glasses: 'sun',
  },
  'preset-08': {
    skinTone: 'amber',
    hair: 'curly',
    hairColor: 'brown',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'square',
  },
  'preset-09': {
    skinTone: 'ivory',
    hair: 'bun',
    hairColor: 'black',
    eyes: 'big',
    mouth: 'pout',
    beard: 'none',
    glasses: 'round',
  },
  'preset-10': {
    skinTone: 'ivory',
    hair: 'sidepart',
    hairColor: 'blonde',
    eyes: 'happy',
    mouth: 'smile',
    beard: 'none',
    glasses: 'none',
  },
  'facu-01': {
    skinTone: 'golden',
    hair: 'crop',
    hairColor: 'espresso',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'none',
  },
  'facu-02': {
    skinTone: 'golden',
    hair: 'crop',
    hairColor: 'espresso',
    eyes: 'round',
    mouth: 'smile',
    beard: 'none',
    glasses: 'square',
  },
  'facu-03': {
    skinTone: 'golden',
    hair: 'crop',
    hairColor: 'espresso',
    eyes: 'round',
    mouth: 'smirk',
    beard: 'stubble',
    glasses: 'none',
  },
  'facu-04': {
    skinTone: 'golden',
    hair: 'crop',
    hairColor: 'espresso',
    eyes: 'brown',
    mouth: 'soft',
    beard: 'none',
    glasses: 'none',
  },
}
